language: php
php:
  - '7.1'

env:
  global:
    - GITHUB_REPO: "hess3077/phoenix"
    - secure: "SfKnd2q/Pr3oBfgf8lZNGhVa1K48AkcMFO3tJp/N6JgMyJtEfvNoj23+B6XBApfY+kr9bgOXve6Kz6Rp+q/6dvufSU8cdLBxXmIaZSvoprZr0+lCUnc0zxTzIHrW9ouciRarOuag5YWwH5PSO23XsAFhK4DS0vuFJBILQBdCmgTVXdqFaPABfm9b5I5Idgq4qua4ZjuNx8QkYnLKaSNsqurWHg8nyn5aGWKPMJwCRxtXgGJVVOUFvL/L1JjqcU7zgwGrpnQ3KFQ8gr+QRPtRMXItGYXcHTGz6jf78VF+PeP5M57vcTxLjW1awohLCjASE1816gzL7mTaKirk+K3Ztk5hdqrQQc1rIKX+ojJkaaisf3rqI//f5ZejQktwDN8JLNNUIMnFQi8AMQd9ZD0IILXyehD+lCrt+POmZoidjFPuO6RPA0vTrA2IHDsCoukyJ8k4tMbixBGqvPpsa78BbLQfBDmGjT60L92zSz5NaKRfTB97BrThfEeJr7OrhouFgcH6cgqFNJoXCm2Oaj7hBYpppWJazk/2jI2axSbBwcm1iLXAe7cdDtxREvbGC/pIi06dkvFiSnaNCDlrD1UqgqXAr2r1rw43XYOb/wYpyowC1deZ9BV8/cJhEiXgPVrn5DZq0ORI5dj4K/3Pi95Gj7JPhbEIVry4grxsZHexylg="

addons:
  sonarcloud:
    organization: "hess3077-github" # the key of the org you chose at step #3
    token:
      secure: "C5K1JSi/KJBWPIYSIr6LcQwDRFLemuBJV5NY5pzr4n40ct69mh9MVtNPyRRN41xCAEo1l6zPa77ghro5JdTo7ml7y17A/fkSl6A4NIm6A682iFkQGBSC3SpqkA4f4sQfrIeuTlRompi1pbtlG1hI07sHe4R28yBNTmHQAhen7Pvw8CC75rVgXDHSXwGZnasFviW/r2VAkBFPCd/nGkw4W8M6sg7IsWp7IKsiKzIvsrR7fb6N/xSBChlnRf4X/B8ZVOYpkv9dlsHprtxkKD6clLrYqYrmx8fAKt7zz7RB078ExH3hJmk0j+t2nJpQiTX7BM4vIxWslwGNcc67iWRO4To+pGmF7HrxGpmnVFHLB6a9NtkOZ1i7gzqRYUXuO0hRo5Y85l0nEoPxzw56fFspyj7mKfvjMcQ4z7LMFmyRizdpsxFLLlTdQSaEjKMGGL+j+zkW+JdCjwNVoSm3FDy7OsU3+QWZRdMS6AuvQFHN9dti+udvax0m/GjrygWJzhKK0/Vbzvb1d/85Mflfe8+XpjDaFqaKpF/OhPK95/6N41nMYRSVX6fA1SJ6IhGXI9+9E8eALwiH4qqXaiH6s4B08gECiFtgrtr7/Kh+t/DtKdh3NuHnOa+fd91qhp555nB/EnW+m1QcKdQ5k5MURVMNa5vyXbPXtRxppNeK/cdyxQE=" # encrypted value of your token

script:
   - composer install
   - vendor/phpunit/phpunit/phpunit
   - sonar-scanner

before_script:
  - cp .env.test .env
  - composer install --no-progress
after_success:
  - vendor/bin/couscous travis-auto-deploy

notifications:
  irc:
    template:
      - "%{repository_slug}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
  email:
    recipients:
      - hess.website@gmail.com
    on_success: change
    on_failure: always
  slack:
    template:
      - "Build <%{build_url}|#%{build_number}: %{commit_subject}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} by %{author} %{result} in %{duration}"
    rooms:
      - hess-kn:FsAjzGENr3KPZr8p6TC7dDVV#app-backend-center