monolog:
    channels: ['cron']
    handlers:
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
        main:
            type:  stream
            path:  '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            # max number of log files to keep
            # defaults to zero, which means infinite files
            max_files: 10
            channels: ["!event"]
        cron:
            level:    info
            type:     rotating_file
            path:     '%kernel.logs_dir%/cron.log'
            channels: [cron]
            max_files: 10
        app:
            level:    info
            type:     rotating_file
            path:     '%kernel.logs_dir%/app.log'
            channels: [app]
            max_files: 10
        doctrine:
            level:    error
            type:     rotating_file
            path:     '%kernel.logs_dir%/doctrine.log'
            channels: [doctrine]
            max_files: 10
        security:
            level:    info
            type:     rotating_file
            path:     '%kernel.logs_dir%/security.log'
            channels: [security]
            max_files: 10
        mail:
            type:         fingers_crossed
            # 500 errors are logged at the critical level
            action_level: critical
            # to also log 400 level errors (but not 404's):
            # action_level: error
            # excluded_404s:
            #     - ^/
            handler:      deduplicated
        deduplicated:
            type:    deduplication
            handler: swift
        swift:
            type:       swift_mailer
            from_email: 'contact@tvcongo.com'
            to_email:
                - 'hess.website@gmail.com'
            
            # or list of recipients
            # to_email:   ['dev1@example.com', 'dev2@example.com', ...]
            subject:    'An Error Occurred! %%message%%'
            level:      debug
            formatter:  monolog.formatter.html
            content_type: text/html
        slack:
            type:       slack
            token:       xoxp-571231712704-571403756273-616786841316-e275bbd5b7bf9698ffc2e0bc96983cf3
            channel:     "#tv-congo"
            bot_name:    TVC-Error
            icon_emoji: :ghost:
            level:      critical