# See https://symfony.com/doc/current/email/dev_environment.html
swiftmailer:
    # send all emails to a specific address
    #delivery_addresses: ['me@example.com']
    host: '%env(MAILER_HOST)%'
    port: '%env(MAILER_PORT)%'
    transport: '%env(MAILER_TRANSPORT)%'
    username: '%env(MAILER_USERNAME)%'
    password: '%env(MAILER_PASSWORD)%'
    spool: { type: memory }